### ISSUE TITLE
💡 [REQUEST] - <Adding Completion Braces in the JSON Input Text Area>

### ISSUE THREAD

**Issue by abhishekjani08** [dear-digital/linter#12]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reference Issues

#9 React Project

## Description

This feature aims to enhance the user experience by providing an autocompletion behavior for braces `{}` and quotation marks `"` inside the textarea.

### Feature Details

- **Autocompletion of Braces**: When a user types an opening curly brace `{` at the end of the text in the textarea, the system will automatically insert a closing curly brace `}`. Similarly, typing an opening quotation mark `"` at the end of the text will insert a closing quotation mark `"`. This will help users write JSON and other text-based content more efficiently.

- **Cursor Positioning**: The system will intelligently position the cursor in between the inserted braces or quotation marks, allowing users to start typing immediately within the pair.

### Benefits

- Streamlines the process of writing JSON code and other text content that requires braces or quotation marks.
- Improves code consistency and reduces potential syntax errors by ensuring balanced pairs of braces and quotation marks.

### Basic Example

![image](https://github.com/dear-digital/linter/assets/88500027/8fcfa6df-f37e-436f-a5c1-d356b6772591)

We can try to add more Autocompletion features in the textarea field.

### Have you given as much information as possible about the feature?

- [X] Yes, I have provided as much as  information for the feature

**Comment by mihir-bombay-studio** [comment]
Feature added by [abhishekjani08](https://github.com/abhishekjani08). Updated the points.md file. Closing the issue.
