### ISSUE TITLE
💡 [REQUEST] - Implementing a feature to store Text Input in browser cookies

### ISSUE THREAD

**Issue by dave-SYD** [dear-digital/linter#13]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reference Issues

#9 React UI

### Description 

This feature aims to enhance user experience by storing the text input provided by the user in the text field within the Editor Component, in browser cookies and adding a logic to display the stored cookie data in the text field on page reloads.

**Feature Details:**

- Store Text Input in cookie or update cookie whenever TextField is updated.
- Load stored JSON code from cookie on page reload.

**Benefits:**

- **Simplicity**: Users of the library can benefit from a straightforward and integrated solution for data storage without the need for external APIs or additional dependencies.
- **Reduced Dependencies**: By offering native cookie storing logic, the project can potentially reduce the number of dependencies required by the application.
- **Flexibility**: Developers can choose to utilize the built-in cookie storage or opt for alternative storage mechanisms, depending on their specific use cases.

### Basic Example

![image](https://github.com/dear-digital/linter/assets/60786062/8e7b3b77-ad2e-439a-baef-909a659dae13)

### Have you given as much information as possible about the feature?

- [X] Yes, I have provided as much as  information for the feature

**Comment by mihir-bombay-studio** [comment]
Feature added by [dave-SYD](https://github.com/dave-SYD). Updated the points.md file. Closing the issue.
