### ISSUE TITLE
💡 [REQUEST] - Add a specialized Contributing md file 

### ISSUE THREAD

**Issue by tanujbordikar** [dear-digital/linter#14]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description 

As I have visited the repository, there is not a devoted contributing.md file. So in this I wanted to create a contributing md file with proper screenshots added and with proper steps added.
Like what are the steps needed to add the linter project  directly from the Github and setup the project locally.

### Basic Example

**example-**
https://github.com/priyankarpal/ProjectsHut/blob/main/contributing.md

### Have you given as much information as possible about the feature?

- [X] Yes, I have provided as much as  information for the feature

**Comment by mihir-bombay-studio** [comment]
Feature added by [tanujbordikar](https://github.com/tanujbordikar). Updated the points.md file. Closing the issue.
