### ISSUE TITLE
💡 [REQUEST] - PropType Validation Missing for Component Props

### ISSUE THREAD

**Issue by kmalap05** [dear-digital/linter#15]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description 

I've noticed that in the LinterButtons and Editor component, there is missing PropTypes validation for the onFormatJSON prop and jsonCode, onJsonChange, updatedJson, error props, which could lead to potential runtime errors or unexpected behavior. PropTypes validation is an essential feature in React that helps ensure the correct types and shapes of props are passed to components, improving code reliability and maintainability.

### Basic Example

_Steps to Reproduce:_
Open the **LinterButtons** component in the codebase.
Observe that the **onFormatJSON** prop is used without proper PropTypes validation.

_Expected Behavior:_
PropTypes validation should be added to the **LinterButtons** component to specify that the **onFormatJSON** prop is required and should be a function.

_Example Fix:_

```
import React from "react";
import PropTypes from "prop-types";

function UserProfile({ username, age, email }) {
  return (
    <div>
      <h2>User Profile</h2>
      <p>Username: {username}</p>
      <p>Age: {age}</p>
      <p>Email: {email}</p>
    </div>
  );
}

// This is most important for the validation check.
UserProfile.propTypes = {
  username: PropTypes.string.isRequired,
  age: PropTypes.number.isRequired,
  email: PropTypes.string.isRequired,
};

export default UserProfile;
```

By adding PropTypes validation for the **onFormatJSON** prop, the codebase will be more resilient to potential errors and will help maintain a higher quality standard. I suggest addressing this issue to ensure proper PropTypes validation for critical component props.

### Have you given as much information as possible about the feature?

- [X] Yes, I have provided as much as  information for the feature

**Comment by mihir-bombay-studio** [comment]
@kmalap05 Thanks for the suggestion but if we think about the project as a whole and how we want to evolve it and use the best practices that are currently being used then it would be a good idea to present a case for using typescript in this project which would also solve this issue. You can add another issue with feature request on how using typescript would be beneficial for PropTypes validation and how we can implement it in this project.
