### ISSUE TITLE
💡 [REQUEST] - Updating the installation.md file

### ISSUE THREAD

**Issue by anishdalvi** [dear-digital/linter#18]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description 

![image](https://github.com/dear-digital/linter/assets/70633140/1f02fe37-74fb-461f-8703-340ee17151e5)

There is not need to specify the specific  package name while installing, instead we can simply use `npm install` to install all the dependencies for our project.
Also, to run our project, we can specify the `npm` commands to run project's frontend and backend concurrently or to run them individually based on the users choice.

_This will make it easier for beginners to setup and run our project._

### Basic Example

**Here is the basic sample:**

![image](https://github.com/dear-digital/linter/assets/70633140/83a4342b-963b-4299-9051-b8fe4d08b535)

### Have you given as much information as possible about the feature?

- [X] Yes, I have provided as much as  information for the feature

**Comment by mihir-bombay-studio** [comment]
Feature added by [anishdalvi](https://github.com/anishdalvi). Updated the points.md file. Closing the issue.
