### ISSUE TITLE
💡 [REQUEST] - Adding a clear button

### ISSUE THREAD

**Issue by tanujbordikar** [dear-digital/linter#21]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description 

In this issue, I will add a clear button with proper function to clear the code written or pasted in the editor column.

### Basic Example

*Screenshots preview:*
![clear button](https://github.com/dear-digital/linter/assets/91179998/66a54dec-ba66-49ba-ba81-8b2d7a962615)

### Have you given as much information as possible about the feature?

- [X] Yes, I have provided as much as  information for the feature

**Comment by tanujbordikar** [comment]
hey @mihir-bombay-studio, Please assign this issue to me to fix this Bug as soon as possible, Thank you!

**Comment by mihir-bombay-studio** [comment]
Feature added by [tanujbordikar](https://github.com/tanujbordikar). Updated the points.md file. Closing the issue.
