### ISSUE TITLE
💡 [REQUEST] -  "Copy to Clipboard" Button

### ISSUE THREAD

**Issue by kmalap05** [dear-digital/linter#23]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description 

Addition of a "Copy to Clipboard" button within the JSON editor of the JSON Code Linter application.

### Basic Example

![image](https://github.com/dear-digital/linter/assets/83391228/3653b794-ef08-4a68-8ed6-6737c5ff06a0)

### Have you given as much information as possible about the feature?

- [X] Yes, I have provided as much as  information for the feature

**Comment by anishdalvi** [comment]
Feature added by @kmalap05 
Updated POINTS.md
