### ISSUE TITLE
💡 [REQUEST] - Cookies should be removed on pressing clear button

### ISSUE THREAD

**Issue by anishdalvi** [dear-digital/linter#29]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description 

The clear button on the webpage is intended to remove the JSON code from the input box, ensuring a fresh start for the user. However, I noticed that even after clicking the clear button, the JSON code still persists in the **cookies** of the page.

Clearing the JSON code from cookies is essential to ensure that users are starting with a clean slate. The persistence of JSON code in cookies can result in unintended behavior when users reload the page or return to it after some time.

It would greatly enhance the user experience if the clear button not only clears the input box but also removes the associated cookie. This would provide a seamless and consistent experience for users who want to start linting JSON code from scratch.

_Before pressing Clear Button_

![image](https://github.com/dear-digital/linter/assets/70633140/4c210444-1814-424b-b80e-d9fb63d0c120)

_After pressing Clear Button_

![image](https://github.com/dear-digital/linter/assets/70633140/32b3a74b-7acb-4e97-b443-b732a350c5d2)

### Basic Example

After clicking the clear button, the JSON code should not only be removed from the input box but also cleared from the cookies of the page. This will provide users with a seamless experience when starting a new JSON linting session.

### Have you given as much information as possible about the feature?

- [X] Yes, I have provided as much as  information for the feature

**Comment by mihir-bombay-studio** [comment]
Make sure that the new code added after pressing the clear button gets added to the cookie too

**Comment by anishdalvi** [comment]
Yes, I have ensured the addition of new code to the cookie after clearing the previous one.

**Comment by anishdalvi** [comment]
Feature added by @anishdalvi  
Updated POINTS.md
