### ISSUE TITLE
💡 [REQUEST] - <Download the Output JSON Code>

### ISSUE THREAD

**Issue by abhishekjani08** [dear-digital/linter#30]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reference Issues

Adding new Feature

### Download Output JSON Feature Enhancement

As part of our ongoing efforts to improve the Linter project's functionality and user experience, we are excited to introduce a new enhancement: the **Download Output JSON** feature.

Currently, the Linter project offers users the ability to input and lint JSON code through a user-friendly text editor. However, once the JSON code is linted and displayed in the output field, users might want to conveniently save this linted output for their projects. This is where the **Download Output JSON** feature comes into play.

Stay tuned for updates as I work on implementing this feature to further enrich the capabilities of Linter.

Best regards,
Abhishek Jani

### Basic Example

![image](https://github.com/dear-digital/linter/assets/88500027/67ed5bd6-57ad-4922-94a7-8b3faaa95f19)

### Have you given as much information as possible about the feature?

- [X] Yes, I have provided as much as  information for the feature

**Comment by anishdalvi** [comment]
Feature added by @abhishekjani08 
Updated POINTS.md
