### ISSUE TITLE
💡 [REQUEST] - UI improvement for the upload file option

### ISSUE THREAD

**Issue by dave-SYD** [dear-digital/linter#32]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reference Issues

#25 Upload JSON File 

### Description 

Currently, the option to load a json file from a local directory is not very visually appealing for a user and has some undesired effects on hover. 

![chrome_kNvI0GtSGf](https://github.com/dear-digital/linter/assets/60786062/06e599d4-b1d2-43e0-881f-ec7794d4d96b)

### Basic Example

It would be useful for the project to make the visual design of this feature more appealing to any user who uses the Linter 

### Have you given as much information as possible about the feature?

- [X] Yes, I have provided as much as  information for the feature

**Comment by anishdalvi** [comment]
Feature Added by @dave-SYD 
Updated Points.md
