### ISSUE TITLE
💡 [REQUEST] - <Adding Icons to Download File and Import File on the Button>

### ISSUE THREAD

**Issue by abhishekjani08** [dear-digital/linter#37]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description 

In the context of this project, I will be enhancing the user interface by incorporating icons onto the "Import File" and "Download File" buttons. This strategic addition aims to improve user experience and visual clarity. By introducing intuitive icons alongside these buttons, users will be able to quickly grasp their respective functionalities, thereby enhancing the overall usability of the application. This effort aligns with the project's goal of creating an efficient and user-friendly JSON Linter tool.

Best Regards,
Abhishek Jani.

### Basic Example

![image](https://github.com/dear-digital/linter/assets/88500027/03cfbad0-ab19-4734-9931-93274d4c7c1c)
Icons like this can be used for Download File purpose.

![image](https://github.com/dear-digital/linter/assets/88500027/61e6ad65-8659-4d51-ad50-c82ddf2f3423)
For import file

### Have you given as much information as possible about the feature?

- [X] Yes, I have provided as much as  information for the feature

**Comment by mihir-bombay-studio** [comment]
@abhishekjani08 since we are using polaris for this project it would be best to use icons from polaris library https://polaris.shopify.com/icons

**Comment by anishdalvi** [comment]
Feature added by @abhishekjani08 
Updated POINTS.md
