### ISSUE TITLE
💡 [REQUEST] - Enhanced Accessibility with Element Labels

### ISSUE THREAD

**Issue by kmalap05** [dear-digital/linter#38]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description 

Improve user experience with concise labels on buttons, fields, and uploads. This feature enhances accessibility, enabling users with disabilities to navigate your app effortlessly.

### Basic Example

![code1](https://github.com/dear-digital/linter/assets/83391228/46681994-ee1b-4fd5-b821-7341a5df093d)

In this code, I've added role="group" to the ButtonGroup to indicate that it's a group of buttons. I've also added the aria-label attribute to the ButtonGroup to provide a label for the group. Additionally, I've used the accessibilityLabel prop for each button to provide an accessible label for screen readers. Finally, I've kept the semantic <button> elements for the buttons themselves.

![code2](https://github.com/dear-digital/linter/assets/83391228/5da08108-2ffc-4ee9-a1b7-dd3c262f7e3e)

In this code, I've added aria-label attributes to the TextField components and the input element for the file upload, as well as to the read-only TextField for output. These accessibility labels help provide context and meaning to these elements for users who rely on screen readers.

### Have you given as much information as possible about the feature?

- [X] Yes, I have provided as much as  information for the feature

**Comment by anishdalvi** [comment]
Feature added by @kmalap05 
Updated POINTS.md
