### ISSUE TITLE
🔍 [DISCOVERY] - Basics of Git and GitHub

### ISSUE THREAD

**Issue by mihir-bombay-studio** [dear-digital/linter#52]
### Is there an existing Discovery issue on this topic?

- [X] I have searched the existing issues

### Objective

Use chatGPT or similar LLMs available to ask the following question.
"Explain the basic functionalities and features of Git and GitHub." 
and follow up questions like:
"What are the advantages of using Git over other version control systems?"

### Expected Outcome

List down only the key insights gained from multiple rounds of questioning.
List all the questions/prompts used below in the comment section

### Example on how to write outcome

> #### Initial Prompt:
> - "Describe what linting is and why it's important in software development."
> 
> #### Recursive Prompts:
> 1. "How do linters work under the hood?"
> 2. "What types of problems can linters catch?"
> 3. "Explain the impact of linting on code quality."
> 4. "How can linting be integrated into a continuous integration (CI) system?"
> .
> .
> .
> 
> #### Outcome:
> 
> ##### Key Insights gained:
> - Linting is the process of checking source code for programmatic and stylistic errors.
> - Linters use static analysis to identify issues without running the code.
> - They can catch syntax errors, potential bugs, or even style guide violations.
> - Linting contributes to better code readability and maintainability.
> - It can be automated and integrated into CI pipelines for consistent code quality.
> .
> .
> .
> 

### Have you provided comprehensive details for this discovery task?

- [X] Yes, I have provided comprehensive details

**Comment by anishdalvi** [comment]
**Initial Prompt:**
- "Explain the basic functionalities and features of Git and GitHub."

**Recursive Prompts:**
1. "What are the advantages of using Git over other version control systems?"
2. "Is Git and GitHub different?"
3. "How does Git handle conflicts, and what strategies can be used to resolve them?"
4. "What language is used in Git?"
5. "What is the correct syntax to add a message to a commit?"
6. "What does the git push command do?"
7. "What is the purpose of `git config` ?"
8. "Is `git pull origin` and `git fetch origin` same?"
9. "What is a clone in GitHub?"
10. "What is a README.md file, and why is it important in a GitHub repository?" 
11. "Explain the difference between a fork and a clone in GitHub."
12. "Describe the role of issues and labels in GitHub repositories."
13. "What is GitHub Pages, and how can it be used to host a website?"
14. "How can you protect sensitive information like API keys in a public GitHub repository?"
15. "Describe the difference between a public and a private GitHub repository."

**Outcome:**

Key Insights gained:

_Functionalities and Features of Git_

-  Git tracks changes and **manages versions** of the code and it is distributed so each developer has a full copy, enabling offline work.

 - It supports **parallel development(branching)** and merging changes along with giving an option to save changes with descriptive messages.

 - Git has a **staging area** where you can selectively choose which changes to include in your next commit and records **history** of changes.

 - It provides tools to **resolve conflicts** that may arise when two or more developers modify the same part of a file.

 - Git allows you to create `tags` for marking specific points in history, such as releases and facilitates collaboration through pushing and pulling.

_Functionalities and Features of GitHub_

- GitHub is a **cloud-based** platform for hosting Git repositories.

- It has a built-in **issue tracking** system using which developers can create **pull requests** to the corresponding **issue** raised and propose changes, allowing for code review and **discussion** before merging.

- **Forking** allows the user to create their own copy of the project, make changes, and submit pull requests to the original repository.

- It also offers team management and access control to facilitate **collaboration** among team members and enables **community** participation and discussions.

- GitHub offers **security** scanning, dependency management, and vulnerability alerts to help keep projects secure.

- It **integrates** with third-party tools and services.

_Advantages of Git_

- Git is distributed in nature that allows for offline work with flexibility.

- It has a high-speed performance, even with large repositories.

- Git has powerful branching and merging capabilities and comes with cross-platform compatibility.

- It provides strong data integrity through cryptographic hashing.

- Git has a Staging area for careful commit crafting.

_Insights from other prompts:_

- Yes, Git and GitHub are **different**; Git is a distributed version control system, while GitHub is a web-based platform for hosting Git repositories and collaborating on software projects.

- Git handles conflicts by marking the conflicting lines in the affected files, and developers can **manually** resolve conflicts by editing the files and then **committing** the changes.

- Git is implemented in the **C programming language**.

- Syntax to add a message to a commit is `git commit -m "Your commit message here"`

- The `git push` command is used to upload local changes to a remote **Git repository**, making them accessible to others.

- The `git config` command is used to set and view Git configuration options, such as user information and repository settings.

- The `git pull origin` command is used to fetch changes from the remote repository specified as 'origin' and integrate them into the current local branch, effectively combining `git fetch origin` and `git merge origin/<branch>`

- In GitHub, a "**clone**" refers to creating a **local copy** of a remote repository on your own machine to work with the repository's code and history.

- A `README.md` file is a **markdown-formatted** document in a GitHub repository that provides essential information about the project, including instructions, documentation, and project details.

- A fork creates a **copy** of a repository under your GitHub account, while a clone makes a **local copy** on your machine.

- **Issues** in GitHub are used for tracking tasks, bugs, and feature requests, and **labels** help categorize and organize them within a repository.

- GitHub Pages is a feature that allows you to **host static websites** directly from your GitHub repository, making it accessible via a specific GitHub URL.

- To protect sensitive information in a public GitHub repository, use environment variables or a `.gitignore` file to exclude such data from version control.

- A public GitHub repository is **visible to anyone**, while a private repository is **accessible only** to specified collaborators with the appropriate permissions.

**Comment by mihir-bombay-studio** [comment]
Thanks @anishdalvi
