### ISSUE TITLE
🔍 [DISCOVERY] - Basics of Markdown

### ISSUE THREAD

**Issue by mihir-bombay-studio** [dear-digital/linter#53]
### Is there an existing Discovery issue on this topic?

- [X] I have searched the existing issues

### Objective

Use chatGPT or similar LLMs available to ask the following question.
"Describe what Markdown is and its uses."
and follow up questions like:
"How does Markdown differ from HTML?"

### Expected Outcome

List down only the key insights gained from multiple rounds of questioning.
List all the questions/prompts used below in the comment section. **You'll directly get points rewarded for this task for adding correct answer as comment**

### Example on how to write outcome

> #### Initial Prompt:
> - "Describe what linting is and why it's important in software development."
> 
> #### Recursive Prompts:
> 1. "How do linters work under the hood?"
> 2. "What types of problems can linters catch?"
> 3. "Explain the impact of linting on code quality."
> 4. "How can linting be integrated into a continuous integration (CI) system?"
> .
> .
> .
> 
> #### Outcome:
> 
> ##### Key Insights gained:
> - Linting is the process of checking source code for programmatic and stylistic errors.
> - Linters use static analysis to identify issues without running the code.
> - They can catch syntax errors, potential bugs, or even style guide violations.
> - Linting contributes to better code readability and maintainability.
> - It can be automated and integrated into CI pipelines for consistent code quality.
> .
> .
> .
> 

### Have you provided comprehensive details for this discovery task?

- [X] Yes, I have provided comprehensive details

**Comment by abhishekjani08** [comment]
Initial Prompt:

- "Describe the basics of Markdown"

Recursive Prompts:

1. What is Markdown?
2. What syntax do you use to create an unordered (bullet) list in Markdown?
3. How can you add hyperlinks to text in a Markdown document?
4. Describe the differences between inline code and code blocks in Markdown. Provide examples of each.
5. Explain how to create ordered (numbered) lists in Markdown.
6. What are Markdown tables, and how do you create them?
7. How can you include images with alt text in a Markdown document?
8. What is a Markdown "escape character," and when would you use it?
9. What is the concept of "Markdown flavors," and can you name and describe some popular Markdown flavors or extensions?
10. How do you create footnotes in Markdown, and what is their purpose?
11. Explain how to create complex layouts and styles in Markdown for web content, such as responsive designs.
13. How can you use Markdown for mathematical notations and equations?

Outcome:

## What is Markdown 

Markdown is a lightweight markup language that allows you to format plain text using simple and intuitive syntax. It is widely used for various purposes, such as creating structured documents, documentation, web content, and more.

## Why Use Markdown?

- **Simplicity**: Markdown uses plain text characters to indicate formatting, making it easy to learn and write.
- **Readability**: Markdown documents are human-readable even in their raw form.
- **Versatility**: Markdown is suitable for creating various types of content, from simple notes to complex web pages.
- **Widely Supported**: Markdown is supported by many text editors, content management systems, and online platforms.

## Basic Markdown Elements

Here are some basic elements of Markdown:

- **Headings**: Create headings using hash symbols (`#`). For example, `# Heading 1`.
- **Emphasis**: Make text bold or italic using asterisks or underscores. For bold, use `**` or `__`, and for italic, use `*` or `_`.
- **Lists**: Create both unordered (bullet) and ordered (numbered) lists.
- **Links**: Add hyperlinks to text using `[text](URL)`.
- **Images**: Include images with alt text using `![alt text](image URL)`.

## Getting Started

1. Install a Markdown editor or use a text editor that supports Markdown.
2. Create a new `.md` file and start writing using Markdown syntax.
3. Preview your document to see how it will appear when rendered.

## Headings

To create headings in Markdown, you can use hash symbols `#`. The number of hash symbols determines the heading level. For example:

```markdown
# Heading 1
## Heading 2
### Heading 3
#### Heading 4
##### Heading 5
###### Heading 6
```
## Emphasis (Bold and Italic)

To add emphasis to your text, use asterisks `*` or underscores `_`:

- To make text **bold**, wrap it with double asterisks or underscores. For example, `**Bold Text**` or `__Bold Text__`.

- To make text *italic*, wrap it with single asterisks or underscores. For example, `*Italic Text*` or `_Italic Text_`.

## Unordered (Bullet) Lists

To create an unordered list, simply use an asterisk `*`, plus `+`, or minus `-` followed by a space. Here's an example:

```markdown
* Item 1
* Item 2
  * Sub-item 2.1
  * Sub-item 2.2
* Item 3
```

## Ordered (Numbered) Lists
To create an ordered list, start each item with a number followed by a period and a space. For example:

```markdown
1. Item 1
2. Item 2
3. Item 3
```

## Links

To create hyperlinks, use the following syntax:

```markdown
[Link Text](URL)
For example, to link to Linter's website, you would write:
[Linter's Website](https://github.com/dear-digital/linter/)
```

## Images
To include images in your Markdown document, use an exclamation mark !, followed by alt text in square brackets [], and the image URL in parentheses ():

```markdown
![Alt Text](Image URL)
```

## Blockquotes

Blockquotes are used for quoting text. You can create blockquotes using the greater-than symbol `>`. For example:
> This is a blockquote.

## Tables

Markdown supports tables for presenting structured data. Tables are created using pipes (`|`) and hyphens (`-`) for formatting:

| Header 1 | Header 2 |
| -------- | -------- |
| Cell 1   | Cell 2   |

```markdown
Syntax:
| Header 1 | Header 2 |
| -------- | -------- |
| Cell 1   | Cell 2   |
```

## Lists with Checkboxes

Markdown allows you to create task lists or to-do lists using checkboxes. To create a checkbox, use `- [ ]` for an unchecked item and `- [x]` for a checked item:

- [ ] Task 1
- [x] Task 2

## Escaping Characters

You can escape special characters in Markdown using a backslash `\`. This prevents Markdown from interpreting them as formatting instructions. For example, to display an asterisk as regular text, use `\*`.


## Markdown vs. HTML

**Markdown** is a lightweight markup language, known for its simplicity and readability. It's primarily used for quick text formatting in documents and web content.

**HTML (Hypertext Markup Language)** is a full-fledged markup language used for structuring, styling, and adding interactivity to web pages.

**Key Differences:**

- **Syntax**: Markdown uses plain text characters for formatting, while HTML uses tags and attributes.

- **Complexity**: Markdown has simpler syntax, making it easier to learn. HTML can be complex, especially for web development.

- **Control**: Markdown offers limited control over content structure and design. HTML provides full control for web development.

Choose Markdown for quick and easy text formatting, and HTML for building and designing web pages.

**Comment by mihir-bombay-studio** [comment]
Thanks @abhishekjani08
