### ISSUE TITLE
💡 [REQUEST] - Set Up React Project and Design Main Editor Component

### ISSUE THREAD

**Issue by mihir-bombay-studio** [dear-digital/linter#7]
### Is there an existing issue for this?

- [X] I have searched the existing issues

#### Objective:
Create a user interface (UI) for a JSON code linter that allows users to paste JSON code and choose between two linting methods: local linting and AI-powered linting.

#### Steps to Complete:
1. **Create a New React Project:**
   - Use Create React App or another React boilerplate to set up a new React project.
   - Organize your project by creating appropriate folders for components, styles, etc.

2. **Choose a UI Framework (Optional but Recommended):**
   - Consider using Shopify Polaris components to maintain a consistent design.

3. **Design the Main Editor Component:**
   - Create a new React component named `Editor`.
   - Inside the `Editor` component, add a text area where users can paste their JSON code.
   - Use appropriate HTML tags and React components for the text area.

4. **Add Two Buttons for Linting Options:**
   - Create a button named **Lint Locally**: This button will be used for linting the JSON code offline. (Note: You are only designing the button at this stage; no logic is required.)
   - Create another button named **Lint with AI API**: This button will be used for linting the JSON code using an AI-powered API endpoint. (Note: Again, no logic is required at this stage.)

5. **Style Your Components:**
   - Apply styling to the text area and buttons to make them visually appealing.
   - If using Shopify Polaris, refer to their documentation for available components and styling options.

6. **Test Your Component:**
   - Make sure your component renders correctly.
   - Test the layout by resizing the window to ensure responsiveness.

7. **Commit and Push Your Changes:**
   - Once you're satisfied with your implementation, commit your changes with a descriptive commit message.
   - Push your changes to your forked repository and submit a pull request for review.

#### Notes:
- Focus on creating a clean and functional UI.
- Backend logic for linting is not required at this stage.
- Refer to React and Shopify Polaris documentation as needed.
- Feel free to ask for help or clarification if you encounter any difficulties.

### Basic Example

Make sure to follow the details correctly, ask if there are any questions. Use LLMs for debuging extensively before submitting.

### Have you given as much information as possible about the feature?

- [X] Yes, I have provided as much as  information for the feature

**Comment by dave-SYD** [comment]
Question concering the Editor Component:

In the Editor component, do we have to create a [seperate textfield](https://infoheap.com/json-validator/) to display the linted JSON code or will the updated code be displayed in the [same input textfield](https://jsonlint.com/
)? 

Online linting tools I've come across use either format so I wanted to confirm if theres a specific design in mind for this project or it's upto our discretion?

**Comment by mihir-bombay-studio** [comment]
It's upto you for now to decide. Having a seperate textfield might be ideal but it's optional for the scope of this task.

**Comment by mihir-bombay-studio** [comment]
Feature added by [dave-SYD](https://github.com/dave-SYD). Updated the points.md file. Closing the issue.
