### ISSUE TITLE
🔍 [DISCOVERY] - Explore gadget.dev and Shopify

### ISSUE THREAD

**Issue by mihir-bombay-studio** [dear-digital/linter#74]
### Is there an existing Discovery issue on this topic?

- [X] I have searched the existing issues

### Objective

Learn the fundamentals of [gadget.dev](https://gadget.dev/) and [Shopify Partner](https://www.shopify.com/partners) by reading documentation, setting up accounts, and implementing an example app.

### Point Value

This assignment is worth **300 points**. Make sure to understand all tasks well before proceeding. Take your time and pay attention to details to secure full points.

#### Step 1: Reading Documentation
- **Gadget.dev Documentation**: Read through the [documentation](https://docs.gadget.dev/) to understand the platform's capabilities. Checkout all the tutorials and their [youtube channel](https://www.youtube.com/@gadget_dev/videos)
- **Shopify Partner Documentation**: Refer to [Shopify’s partner documentation](https://help.shopify.com/en/partners/about) or read their [blogs](https://www.shopify.com/partners/blog).

#### Step 2: Account Creation
- **Gadget.dev**: Create a free account on [Gadget.dev](https://gadget.dev/).
- **Shopify Partner**: Sign up for a free [Shopify partner account](https://partners.shopify.com/signup).

#### Step 3: App Implementation
- Choose one app example from [Gadget.dev Shopify tutorials](https://docs.gadget.dev/guides/tutorials/shopify) and implement it within your Shopify partner account create a [development store](https://help.shopify.com/en/partners/dashboard/managing-stores/development-stores#create-a-development-store) if you have to.

#### Step 4: Video Documentation
- Create a 5-10 minute video explaining:
  1. What you learned from the documentation
  2. Which app example you chose and why
  3. A walkthrough of the implemented app

### Expected Outcome
1. Two created accounts (Gadget.dev and Shopify Partner)
2. One functional app as seen on the gadget tutorial
3. A 5-10 minute video explaining your accomplishments

### Deadline
Please complete this assignment by 11th september  9AM and submit the outcomes as comments below.

### Have you provided comprehensive details for this discovery task?

- [X] Yes, I have provided comprehensive details

**Comment by Mri1662** [comment]
## Learn the fundamentals of [gadget.dev](https://gadget.dev/) and [Shopify Partner](https://www.shopify.com/partners) and implement it within your Shopify partner account create a [development store](https://help.shopify.com/en/partners/dashboard/managing-stores/development-stores#create-a-development-store) if you have to.

1. First to created accounts, one on Gadget.dev and one as a Shopify Partner.
2. Then follow tutorial and create app automated product tagger abd Build a pre-purchase Shopify checkout UI extension

**https://1drv.ms/v/s!AuBNb5ood7_9dnX84IiFHlnGJf0?e=fw3voJ** this link for video.

**Comment by anishdalvi** [comment]
## Explore Gadget.dev and Shopify

1. Created accounts for Gadget.dev and Shopify Partner ✅ 
2. Created an Automated Product-Tagger full stack application 💯 
3. [Implementation Video](https://drive.google.com/file/d/1F9LXPRzZicHt9Nytx3U_cg4sMhtmwnIk/view?usp=drive_link) 🔥

**Comment by abhishekjani08** [comment]
I have successfully completed all the tasks outlined in the 'Learning Gadget.dev and Shopify Partner' assignment. I read through the documentation provided by Gadget.dev and Shopify Partner, created accounts on both platforms, implemented a selected app example from Gadget.dev's tutorials within my Shopify Partner account, and produced a 10-minute video summarizing my progress. The video covers what I learned from the documentation, Automated Product tagger app, and a walkthrough of the implemented app.🚀

Video Link -  [Automated Product Tagger](https://drive.google.com/file/d/1XL2-TcuR4eLMhMbCuCca51JOXhwfKH_p/view?usp=drive_link)

**Comment by mihir-bombay-studio** [comment]
Well done @Mri1662 , @anishdalvi and @abhishekjani08 🚀 🔥 🙌 

Awesome explainations @anishdalvi and @abhishekjani08 🤩
