### ISSUE TITLE
🔍 [DISCOVERY] - Automated Code Quality Checks

### ISSUE THREAD

**Issue by mihir-bombay-studio** [dear-digital/linter#84]
### Is there an existing Discovery issue on this topic?

- [X] I have searched the existing issues

### Objective

Client Scenario: Software company needing automated linting and unit testing on pull requests.

Milestones:

1. Initial Setup: Create a GitHub repository with basic code files that need linting.
2. Workflow Creation: Define a .github/workflows YAML file for GitHub Actions.
3. Linting Setup: Add steps in the workflow to run a linter on the code.
4. Pull Request Test: Simulate a pull request to test the workflow.

**testFile.js**
```
const sum = (a, b) => {
  return a+b;
};

// Missing semicolon and extra spacing
const multiply = (a, b) => { return a * b }

// Unused variable 'c'
const unusedVar = (a, b, c) => {
  return a + b;
};

// '==' should be '==='
if (sum(1, 2) == 3) {
  console.log('This is not type-safe.');
}

// Trailing whitespace at the end of the line
const divide = (a, b) => {  
  if (b === 0) {
    return 'Cannot divide by zero.';
  }
  return a / b;
};

// 'var' instead of 'let' or 'const'
var outdatedVar = "I'm an outdated variable declaration";

// Global variable without declaration
undeclaredVar = 'I am undeclared';

```

### Reference Materials

**FAQs**:

1. **What is linting and why is it important?**
    - Prompts to ask: "Explain linting", "Why is linting important?"
    - Answer: Linting helps to identify code quality issues like syntax errors, stylistic errors, and some logical errors.

2. **What are Pull Requests?**
    - Prompts to ask: "What is a pull request?", "How do pull requests work?"
    - Answer: Pull Requests are a way to propose changes to a codebase and collaborate on those changes with other developers before they are integrated into the main codebase.

3. **What is GitHub Actions?**
    - Prompts to ask: "Explain GitHub Actions", "How do GitHub Actions work?"
    - Answer: GitHub Actions enable automated workflows that allow you to build, test, and deploy code right from GitHub.

4. **What is YAML?**
    - Prompts to ask: "What does YAML stand for?", "What is YAML used for?"
    - Answer: YAML stands for "YAML Ain't Markup Language." It is a human-readable data serialization standard that is often used for configuration files.

5. **What are unit tests?**
    - Prompts to ask: "Explain unit tests", "Why are unit tests important?"
    - Answer: Unit tests are automated tests that verify the behavior of individual units of code, usually functions or methods.

6. **How do I create a GitHub Action?**
    - Prompts to ask: "How do I set up a GitHub Action?", "What are the steps to create a GitHub Action?"
    - Answer: You create a YAML file in a specific directory (.github/workflows) in your GitHub repository. This YAML file defines the workflow.

7. **How to test a workflow with a Pull Request?**
    - Prompts to ask: "How can I test GitHub Actions with a pull request?", "What is the workflow for testing GitHub Actions?"
    - Answer: You can test it by making a pull request from a feature branch to the main/master branch. GitHub Actions will automatically run the workflows defined for pull requests.

8. **How do I create a .github/workflows YAML file?**
    - Prompts to ask: "How do I create a workflow file?", "Where do I place the YAML file for GitHub Actions?"
    - Answer: In your GitHub repository, create a new folder named `.github`, within it another folder named `workflows`, and then create a YAML file to define your workflow.

9. **What are GitHub Actions secrets and should I use them?**
    - Prompts to ask: "What are GitHub secrets?", "Should I use GitHub secrets for this project?"
    - Answer: GitHub Actions secrets allow you to store sensitive information. For this project, you don't need to use secrets.

10. **Can you give an example of a GitHub Action?**
    - Prompts to ask: "Show me a sample GitHub Action", "How does a GitHub Action look in code?"

### Expected Outcome

- Create a GitHub Repository: Initialize a new or use an existing GitHub repository.
- Add Test File: Add the testFile.js containing JavaScript code with intentional linting errors (unused variables and trailing whitespaces).
- Create a .github/workflows directory in the GitHub repository.
- Create a pull request that triggers the github action

Testing Parameters:

1. Workflow must trigger on pull requests.
2. Linting must identify coding style violations and return errors if found.
3. Output logs for linting should be clearly visible in GitHub Actions.
4. Create a 7-15 minute video detailing your process and results

### Deadline
Complete this assignment by 25th September, 9 AM, and submit the outcomes as comments below. Each successful submission will be awarded 250points

### Have you provided comprehensive details for this discovery task?

- [X] Yes, I have provided comprehensive details

**Comment by kmalap05** [comment]
# Automated Code Quality Checks (GitHub Actions)
### Author: Kedar Malap

## Task Details
- Initial Setup: Create a GitHub repository with basic code files that need linting.
- Workflow Creation: Define a .github/workflows YAML file for GitHub Actions.
- Linting Setup: Add steps in the workflow to run a linter on the code.
- Pull Request Test: Simulate a pull request to test the workflow.

## Video Attachment
🚀 [Automated Linting and Unit Testing on Pull Request](https://drive.google.com/file/d/19LfhdP3CMsk4BQOJaKiEcSvMbuocQJlm/view?usp=sharing)

**Comment by Mri1662** [comment]
# Automated Code Quality Checks (GitHub Actions)

# Outcome

- Created a GitHub Repository
- Added Test File name testFile.js containing JavaScript code with intentional linting errors (unused variables and trailing whitespaces).
- Created a .github/workflows directory in the GitHub repository.
- Created a pull request that triggers the github action

# video attachment

🚀 [Automated Linting and Unit Testing on Pull Request](https://drive.google.com/file/d/1TfpG73hg0xynWAkKJoIH0HjeXtiaV8dT/view?usp=sharing)

**Comment by abhishekjani08** [comment]
## Automated Code Quality Checks

## Outcomes and understanding of following things

- Github Actions and making of yaml file
- Workflows and rules
- eslint
- Automated Code Checks
- Pull req and push code

## Video Attachment
Here's a 15min detailed description video which covers the outcome of the given task!
✅[Automated Code Quality Checks](https://drive.google.com/file/d/1V0nkCcJXc54BVmyKm4mGAyf5HcF6FqmP/view?usp=sharing)

**Comment by mihir-bombay-studio** [comment]
Thank you all for perfect implementation and taking it one step further in making test cases @kmalap05 @Mri1662 @abhishekjani08!

Also great understanding and explaination of the subject @kmalap05 and @abhishekjani08 🙌
