### ISSUE TITLE
🔍 [DISCOVERY] - Markdown to PDF Conversion Tool

### ISSUE THREAD

**Issue by mihir-bombay-studio** [dear-digital/linter#91]
### Is there an existing Discovery issue on this topic?

- [X] I have searched the existing issues

## Knowledge Prerequisites

- Markdown Syntax
- PDF Generation Libraries
- Pandoc (or equivalent tool)
- Programming language (depending on the chosen solution)

## Use Case

A content creator drafts a lengthy technical document using markdown syntax, replete with tables, links, and embedded images. Upon completion, they opt to convert the markdown document into a PDF to distribute it to stakeholders who prefer the latter format for offline viewing and printing.

## Possible Solution

Integrate a tool such as Pandoc, which stands out in markdown-to-PDF conversions. Design a user-friendly interface or command-line utility that allows users to specify the input markdown file and desired output location for the PDF. Ensure that the resulting PDF retains all formatting and interactive elements present in the markdown source.

## Acceptance Criteria

1. The generated PDF mirrors all markdown formatting, encapsulating tables, headers, lists, and hyperlinks.
2. The implemented solution should exhibit scalability, thereby facilitating batch conversions, if necessitated.
3. Hyperlinks in the markdown must remain clickable within the PDF.
4. The solution must provide adequate error-handling mechanisms for any unsupported markdown elements.

Deadline: 16 Oct, 2023 0900

**Note**: Make your own assumptions wherever info is lacking. Think from a non technical person's point of view, how they can convert markdown files to pdf files easily. You can work on your own repository for this issue. Demo your working submittion in 5-10minutes video. Link to your repository in your submission comment.

### Have you provided comprehensive details for this discovery task?

- [X] Yes, I have provided comprehensive details

**Comment by mihir-bombay-studio** [comment]
@tanujbordikar Sorry I can't assign this yet because your first week starts from tomorrow. I'm still working on a new contribution strategy. I'll let you know as soon as it's complete. Thanks!

**Comment by tanujbordikar** [comment]
> @tanujbordikar Sorry I can't assign this yet because your first week starts from tomorrow. I'm still working on a new contribution strategy. I'll let you know as soon as it's complete. Thanks!

okay sir!

**Comment by abhishekjani08** [comment]
## Markdown to PDF

✅Github: [Github repository link](https://github.com/abhishekjani08/Markdown-to-pdf)
✅Video: [Video Drive link](https://drive.google.com/file/d/19HgUlXUgnokzOJjvC3vqoxeAboLR-wf3/view?usp=sharing)

### Additional Details:

- I have created a 10-minute video demonstration of the entire solution.
- The video covers both the user interface and command-line utility.

### Some details i forgot to mention in the video:
- While integrating pandoc with my user interface, i can to know that `pandoc-server` is a web server that can perform pandoc conversions. But cannot convert any file to PDF (as it is mentioned in their documentations)
![image](https://github.com/dear-digital/linter/assets/88500027/ae1d1ded-d78e-4e9f-b4d4-c799cb42b591)

- So for solving this issue, i managed to find another package and integrated the npm package `markdown-pdf`, which greatly enhances the conversion process.

![image](https://github.com/dear-digital/linter/assets/88500027/a29d9d69-018f-4c14-9215-6333e97b83ca)

### Final Output: 
User Interface:
![image](https://github.com/dear-digital/linter/assets/88500027/303c605a-5f13-4b46-9ba7-b003c26f2067)

Converted to PDF:
![image](https://github.com/dear-digital/linter/assets/88500027/17a43f75-4e37-4926-a972-c7936bc359a7)

🚀 Thank you!

**Comment by Mri1662** [comment]
# Markdown to PDF Conversion Tool

✅ Github: [github repo link](https://github.com/Mri1662/markdown-to-pdf)
✅ video: [video link](https://1drv.ms/v/s!AtmbjUMZ4JXAgZBRHB6SytebU4l5kg)

## Additional details:

- [X] I have created a 8-minute video demonstration of the entire solution.
- [X] The video covers both the web app and command-line utility.

## pandoc
<img width="832" alt="image" src="https://github.com/dear-digital/linter/assets/103936103/d8c326d8-ca01-49b1-9e55-41861a0898d0">

## Find Output:

### web app

<img width="941" alt="image" src="https://github.com/dear-digital/linter/assets/103936103/c591d9b9-a8cf-4889-afa4-808876c73f6e">

<img width="606" alt="image" src="https://github.com/dear-digital/linter/assets/103936103/3dec670a-e3a9-4d2d-89c4-491a4915b0d8">

## Outcomes 

- [X] 1. The generated PDF mirrors all markdown formatting, encapsulating tables, headers, lists, and hyperlinks.
- [X] 2. The implemented solution should exhibit scalability, thereby facilitating batch conversions, if necessitated.
- [X] 3. Hyperlinks in the markdown must remain clickable within the PDF.
- [X] 4. The solution must provide adequate error-handling mechanisms for any unsupported markdown elements.

🚀 Thank you!

**Comment by kmalap05** [comment]
# Markdown To PDF

✅Github: [Github repository link](https://github.com/kmalap05/Markdown-To-PDF-Converter-Tool)
✅Video: [Video Drive link](https://drive.google.com/file/d/1YyiCdJfytnmF-MR9IsF6qQFuawYy-Zmo/view?usp=sharing)

Additional details:
- [x] I have created a 8-minute video demonstration of the entire solution.
- [x] The video covers User friendly web-app (Vite+React.js, Node.js).

### Tools Used: 
#### Puppeteer
![image](https://github.com/dear-digital/linter/assets/83391228/105bdb59-e76b-43f9-914a-c1de30c32712)
#### Markdown-It
![image](https://github.com/dear-digital/linter/assets/83391228/d559db52-7289-423d-88f4-4e37dfc3e781)

### Final Output (Web-app):
![image](https://github.com/dear-digital/linter/assets/83391228/0fb0ea21-cf72-4f0c-a453-fe0c4568ebb1)
![image](https://github.com/dear-digital/linter/assets/83391228/e3f8aa2b-5d24-43a8-8208-16d3b4a49e3a)

### PDF Generated with all formatings:
![image](https://github.com/dear-digital/linter/assets/83391228/8c2711ec-8841-4ef5-885c-3fd8bcf4157e)

**Comment by anishdalvi** [comment]
# Markdown to PDF Conversion Tool

  🔗 [Github Link](https://github.com/anishdalvi/Markdown-To-PDF) Created a repository for maintaing versions of Code
 
🎥 [Video Link](https://drive.google.com/file/d/1w0FWivbkECwhtIeiweRNTIlLKbiMHRgC/view?usp=sharing) A 10 Minutes explanation of the whole code and a short demo

## Details:

- Used [md-to-pdf](https://www.npmjs.com/package/md-to-pdf) library to serve the purpose of converting Markdown To PDF. It is a great alternative to [Pandoc](https://pandoc.org/index.html) because of its support to retain all formats of markdown document into converted PDF.

- Used **iframe** to get the preview of the PDF converted without downloading.

_**Note**: Complete Details are covered in the video_.

## Screenshots:

1. UI of the Tool

   ![1](https://github.com/dear-digital/linter/assets/70633140/4c35a24c-e362-4d82-a66f-e84c1af08d4b)

2. Converted PDF with retained formats
   
   ![image](https://github.com/dear-digital/linter/assets/70633140/732d90f9-18be-4e8e-b3b8-6146a900ecd9)
